apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  values:
    schedule: '11,26,41,56 * * * *'
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
