apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 2.12.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    ingress:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 1024m 
      enabled: true
      tls:
      - secretName: nextcloud-tls
        hosts:
        - cloud.triqster.eu
    nextcloud:
      configs:
        extra.config.php: |-
          <?php
            $CONFIG = array(
              'overwriteprotocol' => 'https',
            );
          ?>
      host: cloud.triqster.eu
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
    mariadb:
      enabled: true
      architecture: standalone
      auth:
        existingSecret: nextcloud-mariadb
        database: nextcloud
        username: nextcloud
      primary:
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 20Gi
    persistence:
      enabled: true
      size: 200Gi
    startupProbe:
      enabled: true
      failureThreshold: 360
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
